CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_AUDIO_TOKEN = "<audio>"
DEFAULT_VIDEO_TOKEN = "<video>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
DEFAULT_IM_GEN_START_TOKEN = "<im_gen_start>"
DEFAULT_AUDIO_GEN_START_TOKEN = "<au_gen_start>"
DEFAULT_VIDEO_GEN_START_TOKEN = "<vd_gen_start>"
DEFAULT_IM_GEN_END_TOKEN = "<im_gen_end>"
DEFAULT_IM_GEN_TOKEN = "<im_gen>"
DEFAULT_AUDIO_GEN_TOKEN = "<audio_gen>"
DEFAULT_VIDEO_GEN_TOKEN = "<video_gen>"
DEFAULT_AUDIO_GEN_START_TOKEN = "<audio_gen_start>"
DEFAULT_MSK_TOKEN = '<mask_gen>'
DEFAULT_BASE_TOKEN = '<base>'
DEFAULT_BASE_NULL_TOKEN = '<base_null>'

class REPLACEMENT_TYPE:
    INPUT = 0
    BASE = 1
    GEN = 2